hostname = pan.baidu.com,gateway.caixin.com,ipadcms.caixin.com,ap?.bili*i.com, ap?.bili*i.net

# 百度云 2021-07-05 (by ddgksf2013)
https:\/\/pan\.baidu\.com\/rest\/2\.0\/membership\/user url script-response-body https://cdn.jsdelivr.net/gh/ddgksf2013/dev@main/BaiDuCloudProCrack.js

# 哔哩哔哩, 港澳台番剧自动切换地区 & 显示豆瓣评分
^https:\/\/ap(p|i)\.bili(bili|api)\.(com|net)\/(pgc\/view\/v\d\/app\/season|x\/offline\/version)\? url script-response-body https://cdn.jsdelivr.net/gh/arcthur/dotfiles@master/qx/Bili_Auto_regions.js
# 可选, 适用于搜索指定地区的番剧
^https:\/\/ap(p|i)\.bili(bili|api)\.(com|net)\/x\/v\d\/search(\/type)?\?.+?%20(%E6%B8%AF|%E5%8F%B0|%E4%B8%AD)& url script-request-header https://cdn.jsdelivr.net/gh/arcthur/dotfiles@master/qx/Bili_Auto_regions.js