# Don't ask for confirmations
assume_yes = true

# Disable specific steps - same options as the command line flag
disable = ["system", "pnpm"]

# Do not ask to retry failed steps (default: false)
no_retry = true

# Run `sudo -v` to cache credentials at the start of the run; this avoids a
# blocking password prompt in the middle of a possibly-unattended run.
pre_sudo = false

# Cleanup temporary or old files
cleanup = true

[brew]
greedy_cask = true
autoremove = true
