#!/usr/bin/env lua

-- Sketchybar Configuration
-- Migrated from Bash to Lua + SbarLua
-- https://github.com/FelixKratz/SbarLua

-- Ensure Homebrew apps are found when started by launchd
os.execute("export PATH='/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin'")

-- Load helpers (sets up module paths and initializes sbar)
require("helpers")

-- Load main configuration
require("init")
