#!/usr/bin/env bash

declare -A icons=(
    [FaceTime]=":face_time:"
    [Messages]=":messages:"
    [VLC]=":vlc:"
    [Notes]=":notes:"
    [Things]=":things:"
    ["GitHub Desktop"]=":git_hub:"
    ["App Store"]=":app_store:"
    ["Google Chrome"]=":google_chrome:"
    [zoom.us]=":zoom:"
    ["Microsoft Word"]=":microsoft_word:"
    ["Microsoft Teams"]=":microsoft_teams:"
    [WhatsApp]=":whats_app:"
    ["Microsoft Excel"]=":microsoft_excel:"
    ["Microsoft PowerPoint"]=":microsoft_power_point:"
    [Numbers]=":numbers:"
    [Default]=":default:"
    [Element]=":element:"
    [Bear]=":bear:"
    [Notion]=":notion:"
    [Calendar]=":calendar:"
    [Xcode]=":xcode:"
    [Slack]=":slack:"
    ["Sequel Pro"]=":sequel_pro:"
    [Bitwarden]=":bit_warden:"
    ["System Preferences"]=":gear:"
    [Discord]=":discord:"
    [Dropbox]=":dropbox:"
    [$'\u5fae\u4fe1']=":wechat:"
    [Mail]=":mail:"
    [$'\u90ae\u4ef6']=":mail:"
    [Safari]=":safari:"
    [Telegram]=":telegram:"
    [Keynote]=":keynote:"
    [Spotify]=":spotify:"
    [Figma]=":figma:"
    [Spotlight]=":spotlight:"
    [Music]=":music:"
    [Pages]=":pages:"
    [Obsidian]=":obsidian:"
    [Zotero]=":zotero:"
    [Reminders]=":reminders:"
    [Preview]=":pdf:"
    [Code]=":code:"
    [Calibre]=":book:"
    [Finder]=":finder:"
    [Linear]=":linear:"
    [Podcasts]=":podcasts:"
    [Ghostty]=":terminal:"
    [Terminal]=":terminal:"
)

echo "${icons[${1:-}]:-:default:}"
